root = "."
tmp_dir = "tmp"

[build]

cmd = "go build -o ./tmp/main ./cmd/app/main.go"

bin = "./tmp/main"

include_ext = ["go", "tpl", "tmpl", "html"]

exclude_dir = ["tmp", "web", "mocks", "vendor", "sqlc"]

delay = 1000

[log]

color = true