basePath: /api/v1
definitions:
  POS-kasir_internal_common.ErrorResponse:
    properties:
      data: {}
      error: {}
      message:
        type: string
    type: object
  POS-kasir_internal_common.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  POS-kasir_internal_dto.CancellationReasonResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      reason:
        type: string
    type: object
  POS-kasir_internal_dto.CreateUserRequest:
    properties:
      email:
        maxLength: 100
        type: string
      is_active:
        type: boolean
      password:
        maxLength: 100
        minLength: 6
        type: string
      role:
        allOf:
        - $ref: '#/definitions/POS-kasir_internal_repository.UserRole'
        enum:
        - admin
        - manager
        - cashier
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - role
    - username
    type: object
  POS-kasir_internal_dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  POS-kasir_internal_dto.LoginResponse:
    properties:
      Token:
        type: string
      expired_at:
        type: string
      profile:
        $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
    type: object
  POS-kasir_internal_dto.ProfileResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      role:
        $ref: '#/definitions/POS-kasir_internal_repository.UserRole'
      updated_at:
        type: string
      username:
        type: string
    type: object
  POS-kasir_internal_dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
      role:
        $ref: '#/definitions/POS-kasir_internal_repository.UserRole'
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - email
    - password
    - role
    - username
    type: object
  POS-kasir_internal_dto.UpdatePasswordRequest:
    properties:
      new_password:
        maxLength: 32
        minLength: 8
        type: string
      old_password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - new_password
    - old_password
    type: object
  POS-kasir_internal_dto.UpdateUserRequest:
    properties:
      email:
        maxLength: 100
        type: string
      is_active:
        type: boolean
      role:
        allOf:
        - $ref: '#/definitions/POS-kasir_internal_repository.UserRole'
        enum:
        - admin
        - manager
        - cashier
      username:
        maxLength: 50
        minLength: 3
        type: string
    type: object
  POS-kasir_internal_dto.UsersResponse:
    properties:
      pagination:
        $ref: '#/definitions/POS-kasir_pkg_pagination.Pagination'
      users:
        items:
          $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
        type: array
    type: object
  POS-kasir_internal_repository.UserRole:
    enum:
    - admin
    - cashier
    - manager
    type: string
    x-enum-varnames:
    - UserRoleAdmin
    - UserRoleCashier
    - UserRoleManager
  POS-kasir_pkg_pagination.Pagination:
    properties:
      current_page:
        type: integer
      per_page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: POS Kasir API
  title: POS Kasir API
  version: "1.0"
paths:
  /api/v1/cancellation-reasons:
    get:
      responses:
        "200":
          description: List of cancellation reasons
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/POS-kasir_internal_dto.CancellationReasonResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: List cancellation reasons
      tags:
      - Cancellation Reasons
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/POS-kasir_internal_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Logout
      tags:
      - Auth
  /auth/me:
    get:
      consumes:
      - application/json
      description: Get profile
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Get profile
      tags:
      - Auth
  /auth/me/avatar:
    put:
      consumes:
      - multipart/form-data
      description: Update avatar
      parameters:
      - description: Avatar file
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Update avatar
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/POS-kasir_internal_dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Register
      tags:
      - Auth
  /auth/update-password:
    post:
      consumes:
      - application/json
      description: Update password
      parameters:
      - description: Update password request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/POS-kasir_internal_dto.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Update password
      tags:
      - Auth
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve a list of users with pagination, filtering, and sorting
      parameters:
      - default: 1
        description: Page number (default 1)
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page (default 10)
        in: query
        name: limit
        type: integer
      - description: Search by username or email
        in: query
        name: search
        type: string
      - description: Filter by User Role
        enum:
        - admin
        - cashier
        - manager
        in: query
        name: role
        type: string
      - description: Filter by Active Status
        in: query
        name: is_active
        type: boolean
      - description: Filter by Account Status
        enum:
        - active
        - deleted
        - all
        in: query
        name: status
        type: string
      - description: Sort by column
        enum:
        - created_at
        - username
        in: query
        name: sortBy
        type: string
      - description: Sort direction
        enum:
        - asc
        - desc
        in: query
        name: sortOrder
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.UsersResponse'
              type: object
        "400":
          description: Invalid query parameters
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: No users found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/POS-kasir_internal_dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Create user
      tags:
      - Users
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Delete user
      tags:
      - Users
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
              type: object
        "400":
          description: User ID is required
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Get user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/POS-kasir_internal_dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/POS-kasir_internal_dto.ProfileResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "403":
          description: You are not authorized to change user roles
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "409":
          description: Username already exists
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Update user
      tags:
      - Users
  /users/{id}/toggle:
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.SuccessResponse'
        "400":
          description: User ID is required
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/POS-kasir_internal_common.ErrorResponse'
      summary: Toggle user status
      tags:
      - Users
swagger: "2.0"
